### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by pronebird** [robertmryan/AFHTTPSessionOperation#1]
Shouldn't you be wrapping `setExecuting:` and `setFinished:` into `@synchronized()` block? 

Both setters are called from main thread and background thread (from `-(void)start`). `NSOperationQueue` creates separate thread for asynchronous tasks.

**Comment by robertmryan** [comment]
Interesting question: I've never seen Apple advise that in custom accessor methods and it's not in any of their `NSOperation` subclass examples (neither in [Configuring Operations for Concurrent Execution](https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationObjects/OperationObjects.html#//apple_ref/doc/uid/TP40008091-CH101-SW8) nor their new Swift [Advanced NSOperations](https://developer.apple.com/videos/wwdc/2015/?id=226) example).

**Comment by pronebird** [comment]
Well according to documentation:

> isExecuting
> isFinished
> 
> **Your implementations of these methods must be safe to call from other threads simultaneously**. You must also generate the appropriate KVO notifications for the expected key paths when changing the values reported by these methods.

I suppose same goes for `setExecuting` and `setFinished` because they access the same ivars.

**Comment by robertmryan** [comment]
The "Multicore Considerations" section of the [NSOperation class reference](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/NSOperation_class/index.html) says something very similar:

> ### Multicore Considerations
> 
> The `NSOperation` class is itself multicore aware. It is therefore safe to call the methods of an NSOperation object from multiple threads without creating additional locks to synchronize access to the object. This behavior is necessary because an operation typically runs in a separate thread from the one that created and is monitoring it.
> 
> When you subclass `NSOperation`, you must make sure that any overridden methods remain safe to call from multiple threads. If you implement custom methods in your subclass, such as custom data accessors, you must also make sure those methods are thread-safe. Thus, access to any data variables in the operation must be synchronized to prevent potential data corruption. For more information about synchronization, see [Threading Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Multithreading/Introduction/Introduction.html#//apple_ref/doc/uid/10000057i).

I've modified my code accordingly.

It's just fascinating that Apple universally ignores this advice in their own code.

**Comment by pronebird** [comment]
Multi-threading is hard. Thanks for update!
