### ISSUE TITLE
AFHTTPSessionOperation not run on background

### ISSUE THREAD

**Issue by HTKT** [robertmryan/AFHTTPSessionOperation#10]
Thanks for your library.
I used AFHTTPSessionOperation and add it to NSOperationQueue but it always run on main thread. I want that task will be processed on background thread. Please give me some advice for this.

This is my code:

``` objc
   // create opertation
    NSOperation *operation = [AFHTTPSessionOperation operationWithManager:_sessionManager HTTPMethod:@"POST" URLString:apiURL parameters:params uploadProgress: nil downloadProgress: nil 
    success:^(NSURLSessionDataTask * _Nonnull task, id  _Nonnull responseObject) {
        @autoreleasepool{
            if(responseObject) {
                completion(responseObject,nil);
            }
        }
    } failure:^(NSURLSessionDataTask * _Nonnull task, NSError * _Nonnull error) {
        @autoreleasepool{
            NSLog(@"Error: %@", error);
            completion(nil,error);
        }
    }];
    [_opertationQueue addOperation:operation];
```

Thanks for you help.

**Comment by robertmryan** [comment]
This is not a `AFHTTPSessionOperation` issue, but rather central behavior of AFNetworking in general. In short, completion handlers are run on the session manager's `completionQueue`, and if that's `nil`, they run on the main queue. You can change this behavior by specifying the GCD queue you want the completion handlers run upon:

``` objc
AFHTTPSessionManager *sessionManager = [AFHTTPSessionManager manager];
sessionManager.completionQueue = dispatch_queue_create("com.domain.app.networkcompletionqueue", DISPATCH_QUEUE_SERIAL);
```
