### ISSUE TITLE
No method to create operation from NSURLRequest

### ISSUE THREAD

**Issue by gagoyal** [robertmryan/AFHTTPSessionOperation#15]
Is there any specific reason that you have not provided a method to create task using dataTaskWithRequest:completionHandler. My issue is that I want to use your operation and I have NSURLRequest already with HTTPBody set in that. Now using the API that you provided, I cannot set HTTPBody in request. So I want to use dataTaskWithRequest:completionHandler as it accepts parameter of type NSURLRequest directly. 

Please let me know if you faced any issues in implementing it or it is by choice that you did not provide an interface to accept request directly.

**Comment by robertmryan** [comment]
It is there. I suspect you're looking at `AFHTTPSessionOperation`, but take a look at `AFURLSessionOperation`. I am mirroring the `AFHTTPSessionManager` vs `AFURLSessionManager` distinction.

**Comment by robertmryan** [comment]
For example:

```objc
AFURLSessionOperation *operation = [AFURLSessionOperation dataOperationWithManager:manager request:request uploadProgress:nil downloadProgress:nil completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
    if (responseObject == nil || error != nil) {
        NSLog(@"error = %@", error);
        return;
    }
    
    // do something with `responseObject` here
}];

[queue addOperation:operation];
```
