### ISSUE TITLE
(minor) missing parameters in 'auto-filled' method sigs

### ISSUE THREAD

**Issue by mrtristan** [robertmryan/AFHTTPSessionOperation#4]
first of all, great work here... this is greatly easing my (late to the party) migration from AFNetworking 2 -> 3. much appreciated!

just a little super minor thing. here's a screenshot to assist in the description. The 'blocks' are missing the actual parameters and only have the types defined. assuming that's not on purpose. take a look at the success and failure ones specifically

<img width="888" alt="screen shot 2016-01-26 at 1 46 14 pm" src="https://cloud.githubusercontent.com/assets/1546181/12591004/bf053b30-c433-11e5-9a2f-7c9e2d0532d3.png">

**Comment by robertmryan** [comment]
No, that was an oversight on my part given that I was just mirroring the block parameters of AFNetworking's `dataTaskWithHTTPMethod`, which didn't provide parameter names for those blocks, either. But I've fixed this in https://github.com/robertmryan/AFHTTPSessionOperation/commit/ac5be00d89207f4d82454034556bad5e6e4c5560.

Thanks.
