### ISSUE TITLE
Operation went isFinished=YES without being started by the queue

### ISSUE THREAD

**Issue by KevinJue** [robertmryan/AFHTTPSessionOperation#7]
> **\* AFHTTPSessionOperation 0x165a9220 went isFinished=YES without being started by the queue it is in

Problem occured when queue is suspending and an operation is added

@robertmryan can you do something or just explain me witch patch i can do ?

**Comment by robertmryan** [comment]
This should be resolved by https://github.com/robertmryan/AFHTTPSessionOperation/commit/bcb5203e4147551536ffa7069ec12162e495f72d.
